---
title: "LM_prediction"
author: "Arthur Starodynov"
date: "2023-12-02"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(lubridate)
library(readr) 
library("ggplot2") 
library("dplyr")
library(xts)
library("lubridate")
library("RColorBrewer")
library("ggthemes")
library("gridExtra")
library("leaflet")
library("highcharter")
library(scales)
library(leaflet.extras)
library(modelr)
```

```{r}
cleaner_rats <- 
  rats_raw %>%
  drop_na(descriptor, location_type, incident_address, incident_zip,street_name, borough, latitude, longitude) %>%
  select(unique_key, agency, descriptor, location_type, incident_address, incident_zip, street_name, borough,latitude, longitude) %>%
  drop_na() %>%
  janitor::clean_names()

cleaner_rats <- as.data.frame(unclass(cleaner_rats),stringsAsFactors=TRUE)
cleaner_rats
sample_1 <- cleaner_rats[sample(nrow(cleaner_rats), 500), ]
```


```{r}
model1 <-  lm(latitude ~ borough + location_type + incident_zip, data = sample_1)
model2 <-  lm(longitude ~ borough + location_type + incident_zip, data = sample_1)
summary(model1)
summary(model2)


```


```{r}
set.seed(23) 
cleaner_rats1 <- 
  sample_1 %>% 
  select(location_type, borough, latitude)

rats_folds <- crossv_kfold(cleaner_rats1, k = 10)

rats_folds <- rats_folds %>% mutate(model = map(train, ~ lm(latitude ~ ., data = .)))

rats_folds$model[[1]] %>% summary()

```


```{r}
set.seed(23) 
cleaner_rats2 <- 
  sample_1 %>% 
  select(location_type, borough, longitude)

rats_folds2 <- crossv_kfold(cleaner_rats2, k = 10)

rats_folds2 <- rats_folds2 %>% mutate(model = map(train, ~ lm(longitude ~ ., data = .)))

rats_folds2$model[[1]] %>% summary()

```

```{r}
library(broom)

prediction <- 
  rats_folds2 %>%
  mutate(predicted = map2(model, train, ~ augment(.x, newdata = .y))) %>% 
  unnest(predicted)
prediction
```


```{r}
prediction <- prediction %>% 
  mutate(residual = .fitted - longitude)

prediction%>%
  ggplot(aes(longitude, residual)) +
    geom_hline(yintercept = 0) +
    geom_point() +
    stat_smooth(method = "loess") +
    theme_minimal()


```
```{r}
rs <- prediction %>%
  group_by(.id) %>% 
  summarise(
    sst = sum((longitude - mean(longitude)) ^ 2), # Sum of Squares Total
    sse = sum(residual ^ 2),          # Sum of Squares Residual/Error
    r.squared = 1 - sse / sst         # Proportion of variance accounted for
    )

rs %>% 
  ggplot(aes(r.squared, fill  = .id)) +
    geom_histogram() +
    geom_vline(aes(xintercept = mean(r.squared)))

```
